// Build the publishable `gpui-ts` package out of this repo's sources.
//
//   node scripts/build-package.mjs [--host <path-to-host.exe>]
//
// Produces, under packages/gpui-ts/:
//   runtime/index.js    the whole framework API as one ESM file (esbuild)
//   types/*.d.ts        declarations for editors (tsc, flattened to one level)
//   types/index.d.ts    a barrel re-exporting the above
//   vendor/<p>/<a>/     the prebuilt host binary the CLI appends apps to
//
// The runtime is bundled (not published as loose TS) so a user's app resolves a
// *single instance* of the signal store — two copies of `runtime.ts` would mean
// two unrelated signal graphs, and state would silently stop propagating.
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const pkg = path.join(root, "packages", "gpui-ts");

async function loadEsbuild() {
    try {
        return await import("esbuild");
    } catch {
        return import(pathToFileURL(path.join(root, "ui", "node_modules", "esbuild", "lib", "main.js")).href);
    }
}

const argv = process.argv.slice(2);
let host = path.join(root, "host", "target", "release", "gpui-perryts-host.exe");
for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--host") host = path.resolve(argv[++i]);
}

// --- 1. runtime/index.js ----------------------------------------------------
const esbuild = await loadEsbuild();
await esbuild.build({
    entryPoints: [path.join(pkg, "index.ts")],
    outfile: path.join(pkg, "runtime", "index.js"),
    bundle: true,
    format: "esm",
    target: "es2020",
    jsx: "transform",
    jsxFactory: "h",
    jsxFragment: "Fragment",
    charset: "ascii",
    logLevel: "warning",
});
const runtimeSize = fs.statSync(path.join(pkg, "runtime", "index.js")).size;

// --- 2. types/*.d.ts --------------------------------------------------------
// `rootDir` is ui/src, so tsc emits a flat set of files that import each other
// by sibling path (`from "./runtime"`) — which is exactly the layout here.
fs.rmSync(path.join(pkg, "types"), { recursive: true, force: true });
const tsc = path.join(root, "ui", "node_modules", "typescript", "bin", "tsc");
if (!fs.existsSync(tsc)) {
    console.error("[pkg] typescript not found in ui/node_modules — run `npm install` in ui/");
    process.exit(2);
}
execFileSync(process.execPath, [tsc, "-p", path.join(pkg, "tsconfig.types.json")], {
    stdio: "inherit",
});

// `tsc` cannot emit a barrel for a source tree it does not own, and it will not
// flatten `../../ui/src/*` for us — so the entry that `exports.types` points at
// is written here, next to the files it re-exports.
fs.writeFileSync(
    path.join(pkg, "types", "index.d.ts"),
    [
        "// Generated by scripts/build-package.mjs — the public surface of gpui-ts.",
        'export * from "./runtime";',
        'export * from "./kit";',
        'export * from "./canvas2d";',
        'export * from "./theme";',
        "",
    ].join("\n"),
);

// The demo app lives in the same source tree, so tsc emits declarations for it
// too. They are not part of the public surface (nothing re-exports them) and
// would only suggest they are API.
for (const demo of ["app.d.ts", "main.d.ts", "bom.d.ts"]) {
    fs.rmSync(path.join(pkg, "types", demo), { force: true });
}

// --- 3. vendor/<platform>-<arch>/ -------------------------------------------
if (!fs.existsSync(host)) {
    console.error(`[pkg] host not found: ${host}`);
    console.error("      build it first (node scripts/gpui-ts.mjs) or pass --host <path>");
    process.exit(2);
}
const destDir = path.join(pkg, "vendor", `${process.platform}-${process.arch}`);
fs.mkdirSync(destDir, { recursive: true });
const dest = path.join(destDir, "nativets-host.exe");
fs.copyFileSync(host, dest);

const dtsCount = fs.readdirSync(path.join(pkg, "types")).filter((f) => f.endsWith(".d.ts")).length;
console.log(`[pkg] runtime/index.js   ${(runtimeSize / 1024).toFixed(0)} KB`);
console.log(`[pkg] types/             ${dtsCount} declaration files`);
console.log(`[pkg] vendor/${process.platform}-${process.arch}/  ${(fs.statSync(dest).size / 1048576).toFixed(1)} MB`);
console.log("[pkg] done — `npm pack` inside packages/gpui-ts to inspect the tarball");
